linux: &linux
  os: linux
  sudo: required
  language: python
  python: "3.6"
  services:
    - docker

osx: &osx
  os: osx
  language: generic

matrix:
  include:
    # Test supported OSX compilers
    - <<: *osx
      osx_image: xcode10.3
      env:
        - CONAN_APPLE_CLANG_VERSIONS=10.0
    - <<: *osx
      osx_image: xcode11.3
      env:
        - CONAN_APPLE_CLANG_VERSIONS=11.0

    # Test supported boost and asio versions
    - <<: *linux
      env:
        - CONAN_GCC_VERSIONS=7
        - CONAN_DOCKER_IMAGE=conanio/gcc7
        - CONAN_OPTIONS=boost=1.70.0
    - <<: *linux
      env:
        - CONAN_GCC_VERSIONS=7
        - CONAN_DOCKER_IMAGE=conanio/gcc7
        - CONAN_OPTIONS=boost=1.71.0
    - <<: *linux
      env:
        - CONAN_GCC_VERSIONS=7
        - CONAN_DOCKER_IMAGE=conanio/gcc7
        - CONAN_OPTIONS=boost=1.72.0
    - <<: *linux
      env:
        - CONAN_GCC_VERSIONS=7
        - CONAN_DOCKER_IMAGE=conanio/gcc7
        - CONAN_OPTIONS=asio=1.13.0,packio:standalone_asio=True
    - <<: *linux
      env:
        - CONAN_GCC_VERSIONS=7
        - CONAN_DOCKER_IMAGE=conanio/gcc7
        - CONAN_OPTIONS=asio=1.14.0,packio:standalone_asio=True

    # Test supported linux compilers
    - <<: *linux
      env:
        - CONAN_GCC_VERSIONS=7
        - CONAN_DOCKER_IMAGE=conanio/gcc7
    - <<: *linux
      env:
        - CONAN_GCC_VERSIONS=8
        - CONAN_DOCKER_IMAGE=conanio/gcc8
    - <<: *linux
      env:
        - CONAN_GCC_VERSIONS=9
        - CONAN_DOCKER_IMAGE=conanio/gcc9
    - <<: *linux
      env:
        - CONAN_CLANG_VERSIONS=5.0
        - CONAN_DOCKER_IMAGE=conanio/clang50
    - <<: *linux
      env:
        - CONAN_CLANG_VERSIONS=6.0
        - CONAN_DOCKER_IMAGE=conanio/clang60
    - <<: *linux
      env:
        - CONAN_CLANG_VERSIONS=7.0
        - CONAN_DOCKER_IMAGE=conanio/clang70
    - <<: *linux
      env:
        - CONAN_CLANG_VERSIONS=8
        - CONAN_DOCKER_IMAGE=conanio/clang8
    - <<: *linux
      env:
        - CONAN_CLANG_VERSIONS=9
        - CONAN_DOCKER_IMAGE=conanio/clang9

    # Test coroutines
    - <<: *linux
      env:
        - CONAN_CLANG_VERSIONS=9
        - CONAN_DOCKER_IMAGE=conanio/clang9
        - BUILDER_CLANG_COROUTINE=1

    # Test samples, including coroutines
    - <<: *linux
      env:
        - CONAN_CLANG_VERSIONS=9
        - CONAN_DOCKER_IMAGE=conanio/clang9
        - CPT_TEST_FOLDER=samples
        - BUILDER_CLANG_COROUTINE=1

    # Test no RTTI
    - <<: *linux
      env:
        - CONAN_CLANG_VERSIONS=7.0
        - CONAN_DOCKER_IMAGE=conanio/clang70
        - CONAN_OPTIONS=rtti=False

    # Test logs
    - <<: *linux
      env:
        - CONAN_CLANG_VERSIONS=7.0
        - CONAN_DOCKER_IMAGE=conanio/clang70
        - CONAN_OPTIONS=loglevel=trace
      script:
        - chmod +x .ci/run.sh
        # grep-out logs otherwise the job gets killed
        - ./.ci/run.sh | grep -E -v '\[[a-z]+\]'

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
