linux: &linux
  os: linux
  sudo: required
  language: python
  python: "3.6"
  services:
    - docker

osx: &osx
  os: osx
  language: generic

matrix:
  include:
    # Test supported OSX compilers
    - <<: *osx
      osx_image: xcode10.3
      env:
        - CONAN_APPLE_CLANG_VERSIONS=10.0
    - <<: *osx
      osx_image: xcode11.3
      env:
        - CONAN_APPLE_CLANG_VERSIONS=11.0

    # Test supported dependency versions
    - <<: *linux
      env:
        - CONAN_GCC_VERSIONS=7
        - CONAN_DOCKER_IMAGE=conanio/gcc7
        - CONAN_OPTIONS=boost=1.70.0
    - <<: *linux
      env:
        - CONAN_GCC_VERSIONS=7
        - CONAN_DOCKER_IMAGE=conanio/gcc7
        - CONAN_OPTIONS=boost=1.71.0
    - <<: *linux
      env:
        - CONAN_GCC_VERSIONS=7
        - CONAN_DOCKER_IMAGE=conanio/gcc7
        - CONAN_OPTIONS=msgpack=3.0.1
    - <<: *linux
      env:
        - CONAN_GCC_VERSIONS=7
        - CONAN_DOCKER_IMAGE=conanio/gcc7
        - CONAN_OPTIONS=msgpack=3.1.1
    - <<: *linux
      env:
        - CONAN_GCC_VERSIONS=7
        - CONAN_DOCKER_IMAGE=conanio/gcc7
        - CONAN_OPTIONS=msgpack=3.2.0

    # Test supported linux compilers
    - <<: *linux
      env:
        - CONAN_GCC_VERSIONS=7
        - CONAN_DOCKER_IMAGE=conanio/gcc7
    - <<: *linux
      env:
        - CONAN_GCC_VERSIONS=8
        - CONAN_DOCKER_IMAGE=conanio/gcc8
    - <<: *linux
      env:
        - CONAN_GCC_VERSIONS=9
        - CONAN_DOCKER_IMAGE=conanio/gcc9
    - <<: *linux
      env:
        - CONAN_CLANG_VERSIONS=5.0
        - CONAN_DOCKER_IMAGE=conanio/clang50
    - <<: *linux
      env:
        - CONAN_CLANG_VERSIONS=6.0
        - CONAN_DOCKER_IMAGE=conanio/clang60
    - <<: *linux
      env:
        - CONAN_CLANG_VERSIONS=7.0
        - CONAN_DOCKER_IMAGE=conanio/clang70
    - <<: *linux
      env:
        - CONAN_CLANG_VERSIONS=8
        - CONAN_DOCKER_IMAGE=conanio/clang8
    - <<: *linux
      env:
        - CONAN_CLANG_VERSIONS=9
        - CONAN_DOCKER_IMAGE=conanio/clang9

    # Test samples
    - <<: *linux
      env:
        - CONAN_GCC_VERSIONS=9
        - CONAN_DOCKER_IMAGE=conanio/gcc9
        - CPT_TEST_FOLDER=samples

    # Test options
    - <<: *linux
      env:
        - CONAN_GCC_VERSIONS=8
        - CONAN_DOCKER_IMAGE=conanio/gcc8
        - CONAN_OPTIONS=loglevel=trace
      script:
        - chmod +x .ci/run.sh
        # redirect logs to dev/null otherwise the job gets killed
        - ./.ci/run.sh 2>&1 > /dev/null

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
