language: python
python: "3.7"
dist: xenial
install:
  - pip3 install conan
script:
  - CONAN_DEFAULT_PROFILE_PATH=$(realpath ./.ci/profiles/$PROFILE) conan create . --build=missing

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["g++-7"]
      env:
        - PROFILE=g++-7

    - compiler: gcc
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["g++-8"]
      env:
        - PROFILE=g++-8

    - compiler: gcc
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["g++-9"]
      env:
        - PROFILE=g++-9

    - compiler: clang
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["clang-5.0", "g++-7"]
      env:
        - PROFILE=clang++-5.0

    - compiler: clang
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-6.0"]
          packages: ["clang-6.0", "g++-7"]
      env:
        - PROFILE=clang++-6.0

    - compiler: clang
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-7"]
          packages: ["clang-7", "g++-7"]
      env:
        - PROFILE=clang++-7

    - compiler: clang
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-8"]
          packages: ["clang-8", "g++-8"]
      env:
        - PROFILE=clang++-8

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages: ["clang-9", "g++-9"]
      env:
        - PROFILE=clang++-9

    - compiler: gcc
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["g++-8"]
      env:
        - PROFILE=boost-1.70.0

    - compiler: gcc
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["g++-8"]
      env:
        - PROFILE=boost-1.71.0

    - compiler: gcc
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["g++-8"]
      env:
        - PROFILE=msgpack-3.0.1

    - compiler: gcc
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["g++-8"]
      env:
        - PROFILE=msgpack-3.1.1

    - compiler: gcc
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["g++-8"]
      env:
        - PROFILE=msgpack-3.2.0
