build: false

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_OPTIONS: boost=1.70.0
      CONAN_VISUAL_RUNTIMES: MD
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_OPTIONS: boost=1.71.0
      CONAN_VISUAL_RUNTIMES: MD
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_OPTIONS: msgpack=3.0.1
      CONAN_VISUAL_RUNTIMES: MD
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_OPTIONS: msgpack=3.1.1
      CONAN_VISUAL_RUNTIMES: MD
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_OPTIONS: msgpack=3.2.0
      CONAN_VISUAL_RUNTIMES: MD

install:
  - pip.exe install conan_package_tools --upgrade
  - conan user # It creates the conan data directory

test_script:
  - python build.py
