build: false

environment:
  global:
    CONAN_REQUEST_TIMEOUT: 300

  matrix:
    # Linux job
    - job_name: Linux build
      job_group: Build
      appveyor_build_worker_image: Ubuntu2004

    # Mac job
    - job_name: MacOS build
      job_group: Build
      appveyor_build_worker_image: macos

    # Windows job
    - job_name: Windows build
      job_group: Build
      appveyor_build_worker_image: Visual Studio 2019

for:

  -
    matrix:
      only:
        - job_name: Linux build

    install:
      - source ~/venv3.7/bin/activate
      - python -m pip install -U conan conan_package_tools
      - sudo apt-get update
      - sudo apt-get install -y
          clang-6.0 clang-7 clang-8 clang-9 clang-10
          g++-7 g++-8 g++-9 g++-10
          libc++-10-dev libc++abi-10-dev

  -
    matrix:
      only:
        - job_name: MacOS build

    install:
      - source ~/venv3.7/bin/activate
      - python -m pip install -U conan conan_package_tools

  -
    matrix:
      only:
        - job_name: Windows build

    install:
      - SET PATH=C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%
      - python -m pip install -U conan conan_package_tools

build_script:
  - python .ci/build.py
